name: nutrisync
description: Aplicación de control calórico con IA - NutriSync by Bytezon

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  # Base de datos local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Manejo de estado
  provider: ^6.1.1
  
  # Cámara y galería
  image_picker: ^1.1.0
  
  # API calls
  http: ^1.2.0
  
  # Gráficos
  fl_chart: ^0.66.0
  
  # Navegación
  go_router: ^14.0.0
  
  # Utilidades
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  pedometer: ^4.1.1
  permission_handler: ^11.3.1
  
  # UI
  flutter_svg: ^2.0.10
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.2.2
  youtube_player_flutter: ^9.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  
  # Generadores de código
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  
  # JSON serialization
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true

  assets:
    - assets/Imagenes/
    - assets/icons/
    - assets/Gif/
    - assets/data/
    - assets/gifs/
    
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf

# Configuración de iconos de la aplicación
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/Icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/Icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/Icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/Icon.png"
